name: .NET Build & Test

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        dotnet-version: [8.0.x]
        test-type: [unit-tests, integration-tests]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        uses: ./.github/actions/test-dotnet
        with:
          type: ${{ matrix.test-type }}
          project-id: ${{ secrets.PROJECT_ID }}
          dotnet-version: ${{ matrix.dotnet-version }}